codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*.spec.ts"
  - "**/*.e2e-spec.ts"
  - "**/dto/**"
  - "**/entities/**"
  - "test/**"
  - "prisma/**"
  - "uploads/**"
  - "**/*.module.ts"
  - "main.ts"
